### ISSUE TITLE
Unused styles cannot be detected if a component is wrapped inside `memo`

### ISSUE THREAD

**Issue by chsdwn** [RodSarhan/eslint-plugin-react-native-unistyles#5]
- `package.json`:

```json
{
  "dependencies": {
    "eslint": "^8.57.0",
    "eslint-plugin-react-native-unistyles": "^0.2.9",
    "react-native-unistyles": "^2.8.4"
  }
}
```

- Please check screenshots below:

<div style="display: flex;">
  <img width="400" alt="Screenshot 2024-11-05 at 14 58 38" src="https://github.com/user-attachments/assets/2948b000-e51e-4d67-b0fa-8c549dcf993d">
  <img width="400" alt="Screenshot 2024-11-05 at 14 59 09" src="https://github.com/user-attachments/assets/b93ad0fd-a351-46f3-9939-5482b5633771">
</div>

**Comment by RodSarhan** [comment]
Thanks for the report, i expect it also won't work for any wrapper or HOC too.
Will try to take a look this weekend.

**Comment by RodSarhan** [comment]
Greetings @chsdwn ,
As we're waiting for v3 release, i can't promise an update to this plugin for v2, but in order to solve your case you can just do the following to fix component detection.

```
const MyComponent = () => {};
export const MyMemoizedComponent = memo(MyComponent);
```
